volumes:
  comet_data:

services:
  comet:
    container_name: comet
    image: g0ldyy/comet
    restart: unless-stopped
    ports:
      - "1338:1338"
    environment:
      - ADDON_ID=${ADDON_ID}
      - ADDON_NAME=${ADDON_NAME}
      - FASTAPI_HOST=${FASTAPI_HOST}
      - FASTAPI_PORT=${FASTAPI_PORT}
      - FASTAPI_WORKERS=${FASTAPI_WORKERS}
      - DASHBOARD_ADMIN_PASSWORD=${DASHBOARD_ADMIN_PASSWORD}
      - DATABASE_TYPE=${DATABASE_TYPE}
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_PATH=${DATABASE_PATH}
      - CACHE_TTL=${CACHE_TTL}
      - DEBRID_PROXY_URL=${DEBRID_PROXY_URL}
      - INDEXER_MANAGER_TYPE=${INDEXER_MANAGER_TYPE}
      - INDEXER_MANAGER_URL=${INDEXER_MANAGER_URL}
      - INDEXER_MANAGER_API_KEY=${INDEXER_MANAGER_API_KEY}
      - INDEXER_MANAGER_TIMEOUT=${INDEXER_MANAGER_TIMEOUT}
      - INDEXER_MANAGER_INDEXERS=${INDEXER_MANAGER_INDEXERS}
      - GET_TORRENT_TIMEOUT=${GET_TORRENT_TIMEOUT}
      - ZILEAN_URL=${ZILEAN_URL}
      - ZILEAN_TAKE_FIRST=${ZILEAN_TAKE_FIRST}
      - SCRAPE_TORRENTIO=${SCRAPE_TORRENTIO}
      - PROXY_DEBRID_STREAM=${PROXY_DEBRID_STREAM}
      - PROXY_DEBRID_STREAM_PASSWORD=${PROXY_DEBRID_STREAM_PASSWORD}
      - PROXY_DEBRID_STREAM_MAX_CONNECTIONS=${PROXY_DEBRID_STREAM_MAX_CONNECTIONS}
      - PROXY_DEBRID_STREAM_DEBRID_DEFAULT_SERVICE=${PROXY_DEBRID_STREAM_DEBRID_DEFAULT_SERVICE}
      - PROXY_DEBRID_STREAM_DEBRID_DEFAULT_APIKEY=${PROXY_DEBRID_STREAM_DEBRID_DEFAULT_APIKEY}
      - TITLE_MATCH_CHECK=${TITLE_MATCH_CHECK}
      - CUSTOM_HEADER_HTML=${CUSTOM_HEADER_HTML}
    volumes:
      - comet_data:/data
